/**
 * Onboarding Page
 *
 * Chat-style onboarding where Harvey asks questions to understand:
 * - What project the user is working on
 * - Their availability and schedule constraints
 * - Their work preferences (morning/evening, rest days, capacity)
 *
 * Architecture:
 * - Uses modular components from @/components/onboarding
 * - Messages are stored in state (currently hardcoded, ready for AI)
 * - ChatInput ready for user input (currently hidden, for future AI)
 *
 * Current State: Hardcoded conversation showing the full flow
 *
 * FUTURE AI INTEGRATION:
 * 1. Replace INITIAL_MESSAGES with empty array
 * 2. Show ChatInput component (uncomment in render)
 * 3. Connect to AI API for Harvey's responses
 * 4. Update progress based on conversation state
 * 5. Extract onboarding data from conversation
 *
 * Flow: User completes conversation → clicks "Build my schedule" → navigates to /loading
 */

'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'

// Import all onboarding components from the centralized index
import {
  ChatMessageList,
  OnboardingProgress,
  OnboardingHeader,
  OnboardingCTA,
  // ChatInput, // Uncomment for future AI integration
} from '@/components/onboarding'

// Import types and helper functions for messages
import type { ChatMessage } from '@/lib/types/chat.types'
import { harveyMessage, userMessage } from '@/lib/types/chat.types'

/**
 * Initial hardcoded messages for the onboarding conversation
 *
 * This array contains the demo conversation shown during onboarding.
 * Each message is created using helper functions that generate proper ChatMessage objects.
 *
 * FUTURE AI INTEGRATION:
 * - Replace this with an empty array: useState<ChatMessage[]>([])
 * - Harvey's first message will be generated by the AI
 * - User will type responses using ChatInput component
 * - AI will respond based on conversation context
 * - Extract OnboardingData from the conversation for schedule generation
 */
const INITIAL_MESSAGES: ChatMessage[] = [
  // Message 1: Harvey's welcome and first question
  harveyMessage(
    "Hey! I'm Harvey, your AI project coach. I'm here to turn \"I want to build something\" into \"Here's exactly what to do today.\" Let's start with the basics - what project are you working on?"
  ),

  // Message 2: User describes their project
  userMessage(
    "I'm building Harvey - an AI accountability coach that helps people with side projects break down their ideas into daily tasks and stay on track."
  ),

  // Message 3: Harvey acknowledges and asks about availability
  harveyMessage(
    "Love it! That's exactly the kind of project I'm built for. Now, when can you actually work on this? Tell me about your schedule - work hours, commute, any existing commitments."
  ),

  // Message 4: User shares their schedule
  userMessage(
    "I work 9am-5:30pm with a 2-hour commute. So I'm free evenings from 8pm and weekends. I also want to keep up my workout routine."
  ),

  // Message 5: Harvey asks about work preferences
  harveyMessage(
    'Perfect! A few more questions: Are you more productive in the morning or evening? How many hours per day can you dedicate? Any days you want to keep as rest days?'
  ),

  // Message 6: User shares their preferences
  userMessage(
    "Definitely evenings - I'm a night owl. I can do 2-3 hours on weeknights, more on weekends. Let's keep Fridays light, that's when I'm usually exhausted."
  ),

  // Message 7: Harvey confirms readiness to build schedule
  harveyMessage(
    "That's everything I need! I've got a clear picture of your goals, constraints, and work style. Ready to see your custom roadmap? I'll break down Harvey's development into specific, executable tasks scheduled around your life."
  ),

  // Message 8: User confirms they're ready
  userMessage("Let's do it! 🚀"),
]

/**
 * User information for displaying in chat
 *
 * FUTURE: This should come from the authenticated user's profile
 * - Get user's name from Supabase auth or database
 * - Compute initial from first letter of name
 */
const USER_INFO = {
  name: 'Milhane',
  initial: 'M',
}

export default function OnboardingPage() {
  const router = useRouter()

  // ===== STATE MANAGEMENT =====

  /**
   * Chat messages state
   *
   * Currently initialized with hardcoded demo messages.
   * The messages array contains all messages in the conversation.
   *
   * FUTURE AI INTEGRATION:
   * - Initialize with empty array or just Harvey's first message
   * - Add new messages as conversation progresses
   * - Use setMessages to append new messages
   */
  const [messages] = useState<ChatMessage[]>(INITIAL_MESSAGES)

  /**
   * Loading state for the CTA button
   * Shows spinner when user clicks "Build my schedule"
   */
  const [isBuilding, setIsBuilding] = useState(false)

  /**
   * Whether Harvey is currently typing/generating a response
   *
   * FUTURE AI INTEGRATION:
   * - Set to true when waiting for AI response
   * - Set to false when response is complete
   * - Used to show typing indicator and disable input
   */
  // const [isTyping, setIsTyping] = useState(false)

  /**
   * Conversation completion state
   *
   * Determines whether to show CTA button or chat input.
   * Currently always true since conversation is hardcoded.
   *
   * FUTURE AI INTEGRATION:
   * - Set to true when AI determines all info has been gathered
   * - Could be based on AI response or specific conversation length
   */
  const isComplete = true

  /**
   * Progress percentage for the progress bar
   *
   * Currently hardcoded to 100% since conversation is complete.
   *
   * FUTURE AI INTEGRATION:
   * - Calculate based on information gathered
   * - Could track: project info (25%), schedule (50%), preferences (75%), complete (100%)
   */
  const progressPercentage = 100

  // ===== EVENT HANDLERS =====

  /**
   * Handle "Build my schedule" button click
   *
   * Called when user clicks the CTA button after completing onboarding.
   * Navigates to the loading page where AI generates the schedule.
   *
   * FUTURE ENHANCEMENTS:
   * - Save onboarding data to database before navigating
   * - Pass extracted data via URL params or context
   */
  const handleBuildSchedule = async () => {
    try {
      setIsBuilding(true)
      console.log('[OnboardingPage] Building schedule, navigating to loading...')

      // FUTURE: Save onboarding data to database
      // const extractedData = extractOnboardingData(messages)
      // await saveOnboardingData(userId, extractedData)

      router.push('/loading')
    } catch (error) {
      console.error('[OnboardingPage] Navigation error:', error)
      setIsBuilding(false)
    }
  }

  /**
   * Handle new message from user
   *
   * Called when user submits a message via ChatInput.
   * Currently commented out - will be used for AI integration.
   *
   * FUTURE AI INTEGRATION:
   * 1. Add user message to messages state immediately (optimistic update)
   * 2. Set isTyping to true
   * 3. Send conversation to AI API
   * 4. Stream Harvey's response (or wait for full response)
   * 5. Add Harvey's response to messages
   * 6. Set isTyping to false
   * 7. Check if conversation is complete
   * 8. Update progress percentage
   *
   * @param content - The message text from the user
   */
  // const handleSendMessage = async (content: string) => {
  //   // Add user message to state
  //   const newUserMessage = userMessage(content)
  //   setMessages(prev => [...prev, newUserMessage])
  //
  //   // Show typing indicator
  //   setIsTyping(true)
  //
  //   try {
  //     // Send to AI API and get response
  //     // const response = await sendToHarveyAI(messages, content)
  //
  //     // Add Harvey's response
  //     // setMessages(prev => [...prev, harveyMessage(response)])
  //
  //     // Check if conversation is complete
  //     // if (isConversationComplete(response)) {
  //     //   setIsComplete(true)
  //     // }
  //   } catch (error) {
  //     console.error('[OnboardingPage] AI error:', error)
  //     // Handle error - maybe add error message to chat
  //   } finally {
  //     setIsTyping(false)
  //   }
  // }

  // ===== RENDER =====

  return (
    <div className="relative flex h-screen w-full flex-col overflow-x-hidden bg-[#FAF9F6]">
      {/*
        Progress Header
        Shows current step and completion percentage
      */}
      <OnboardingProgress
        percentage={progressPercentage}
        currentStep="Onboarding Complete"
        isComplete={isComplete}
      />

      {/* Main Chat Area - Scrollable */}
      <div className="flex-1 flex flex-col items-center justify-start px-4 py-10 overflow-y-auto">
        <div className="w-full max-w-[700px] flex flex-col gap-6">
          {/*
            Success Header
            Only shown when conversation is complete
            Displays celebratory message before CTA
          */}
          {isComplete && (
            <OnboardingHeader
              badgeText="Success"
              headline="The finish line is just the beginning."
              highlightText="the beginning."
            />
          )}

          {/*
            Chat Conversation
            Renders all messages using the ChatMessageList component
            Each message is displayed with appropriate styling for Harvey or user
          */}
          <ChatMessageList
            messages={messages}
            userInitial={USER_INFO.initial}
          />
        </div>
      </div>

      {/*
        Bottom Section
        Shows either:
        - CTA button when conversation is complete
        - ChatInput when conversation is ongoing (future AI)
      */}
      {isComplete ? (
        // Show CTA button when onboarding conversation is complete
        <OnboardingCTA
          onClick={handleBuildSchedule}
          isLoading={isBuilding}
        />
      ) : (
        // FUTURE AI INTEGRATION:
        // Show ChatInput when conversation is ongoing
        // Uncomment the import at the top and this section:
        //
        // <ChatInput
        //   onSend={handleSendMessage}
        //   isLoading={isTyping}
        //   placeholder="Type your answer..."
        //   autoFocus
        // />
        null
      )}

      {/* Background Gradient Decorations - Purely aesthetic */}
      <div className="fixed top-[-10%] left-[-5%] w-[40%] h-[40%] bg-[#8B5CF6]/5 rounded-full blur-[100px] -z-10" />
      <div className="fixed bottom-[-10%] right-[-5%] w-[30%] h-[30%] bg-[#8B5CF6]/10 rounded-full blur-[80px] -z-10" />
    </div>
  )
}
